// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlrratamkejbxlzmhkyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpscnJhdGFta2VqYnhsem1oa3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODY3NzksImV4cCI6MjA3NDY2Mjc3OX0.NTKsU8pPpXlJTApnKNTElRz7cpP7CWWsfa9TtIipfvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});